### ISSUE TITLE
Image upload (WithFileUploads) function don't work with livewire-wizard

### ISSUE THREAD

**Issue by luscalopez** [vildanbina/livewire-wizard#16]
When i try to use the script 
In: Livewire wizardcomponent
`
use Livewire\WithFileUploads;
class CreateCampanha extends WizardComponent
{
    use WithFileUploads;
    public $photo;
...
`
Blade: 
` 
...
<input type="file" wire:model="photo">`
And in Step controller:
`
 public function save()
    {
        $this->validate([
            'photo' => 'image|max:1024', // 1MB Max
        ]);
 
        $this->photo->store('photos');
    }
`
But when the send button is pressed it gives this error **Call to a member function store() on null** this error seems to inform that no file was selected in the input

**Comment by adishardis** [comment]
Did you ever solve it? I'm also having trouble uploading an avatar and showing it.

**Comment by vildanbina** [comment]
I understand your concern, but the problem is that you haven't used the package properly. Below you can find the full code on how to save a photo using the package.

Firstly, we implement `WithFileUploads` in the main Livewire component.

```php
<?php

namespace App\Http\Livewire;

use App\Models\User;
use App\Steps\General;
use Livewire\WithFileUploads;
use Vildanbina\LivewireWizard\WizardComponent;

class UserWizard extends WizardComponent
{
    use WithFileUploads;

    public array $steps = [
        General::class,
        // Other steps...
    ];
    // My custom class property
    public $userId;

    /*
     * Will return App\Models\User instance or will create empty User (based on $userId parameter)
     */
    public function model()
    {
        return new User;
    }
}
```

Then in the class for the step, we need to define all the logic that will interact with the photo, as in the example below:

```php
<?php

namespace App\Steps;

use Vildanbina\LivewireWizard\Components\Step;

class General extends Step
{
    // Step view located at resources/views/steps/general.blade.php
    protected string $view = 'steps.general';

    /*
     * Initialize step fields
     */
    public function mount()
    {
        $this->mergeState([
            'photo' => $this->model->photo,
        ]);
    }

    /*
     * When Wizard Form has submitted
     */
    public function save($state)
    {
        $state['photo']->store('photos');
    }

    /*
     * Step Validation
     */
    public function validate()
    {
        return [
            [
                'state.photo' => 'image|max:1024',
            ],
        ];
    }

    /*
     * Step Title
     */
    public function title(): string
    {
        return __('General');
    }
}
```

And in the view of that step, we need to display the input to allow users to upload a file.

```html
<input type="file" wire:model="state.photo">
```


**Note:** Don't forget to set `state.photo` in the `wire:model` attribute, as only in this way the package will handle it, otherwise it won't work.



If you have any unclear things, please present them in the comments.

**Comment by chugas** [comment]
Hello, when trying to upload multiple files it doesn't work. Below is the example code that I am using.

`<div class="mt-4 text-sm leading-6 text-gray-600">
    <label for="file-upload"
        class="relative cursor-pointer rounded-md bg-white font-semibold text-sky-600 focus-within:outline-none focus-within:ring-2 focus-within:ring-indigo-600 focus-within:ring-offset-2 hover:text-indigo-500">
        <span>Seleccionar archivos</span>
        <input wire:model="state.photos" id="file-upload" name="file-upload"
            type="file" multiple class="sr-only">
    </label>

    @error('state.photos.*')
        <div class="block text-[#ef5350] text-[.8125rem] mt-2">{{ $message }}</div>
    @enderror
</div>`

And the class for the step:

`<?php

namespace App\Http\Livewire\Steps;

use Vildanbina\LivewireWizard\Components\Step;

class Step3 extends Step
{
    protected string $view = 'apps.portal.wizard.steps.step3';

    /*
     * Initialize step fields
     */
    public function mount()
    {
        $this->mergeState([
            'photos' => [],
        ]);
    }
    
    /*
    * Step icon 
    */
    public function icon(): string
    {
        return 'check';
    }

    /*
     * When Wizard Form has submitted
     */
    public function save($state)
    {
        // 
    }

    /*
     * Step Title
     */
    public function title(): string
    {
        return __('Step 3');
    }

    public function validate()
    {
        return [            
        [
            'state.photos' => ['required', 'file', 'mimes:pdf,doc,docx,jpg,jpeg,png,txt', 'max:4096'],
        ], [], []];
    }
}`

Could you help me resolve this?

**Comment by chugas** [comment]
Hello, when trying to upload multiple files it work but the validation is not processed when advancing in the wizard; the validation always passes. Below is the example code that I am using.

```html
<div class="mt-4 text-sm leading-6 text-gray-600">
    <label for="file-upload"
        class="relative cursor-pointer rounded-md bg-white font-semibold text-sky-600 focus-within:outline-none focus-within:ring-2 focus-within:ring-indigo-600 focus-within:ring-offset-2 hover:text-indigo-500">
        <span>Seleccionar archivos</span>
        <input wire:model="state.photos" id="file-upload" name="file-upload"
            type="file" multiple class="sr-only">
    </label>

    @error('state.photos.*')
        <div class="block text-[#ef5350] text-[.8125rem] mt-2">{{ $message }}</div>
    @enderror
</div>
```
And the class for the step:

```php
<?php

namespace App\Http\Livewire\Steps;

use Vildanbina\LivewireWizard\Components\Step;

class Step3 extends Step
{
    protected string $view = 'apps.portal.wizard.steps.step3';

    /*
     * Initialize step fields
     */
    public function mount()
    {
        $this->mergeState([
            'photos' => [],
        ]);
    }
    
    /*
    * Step icon 
    */
    public function icon(): string
    {
        return 'check';
    }

    /*
     * When Wizard Form has submitted
     */
    public function save($state)
    {
        // 
    }

    /*
     * Step Title
     */
    public function title(): string
    {
        return __('Step 3');
    }

    public function validate()
    {
        return [            
        [
            'state.photos.*' => ['required', 'file', 'mimes:pdf,doc,docx,jpg,jpeg,png,txt', 'max:4096'],
        ], [], []];
    }
}
```
Could you help me resolve this?
