### ISSUE TITLE
Hook issue

### ISSUE THREAD

**Issue by rabol** [vildanbina/livewire-wizard#19]
Looks like the hook is not working as described in the doc

```
    public function onStepIn($name, $value)
    {
        // Something you want
        Log::debug("here :{$name}, {$value}" . get_class($this));
    }
```

Too few arguments to function App\Classes\WizardSteps\DocTemplate\UploadTemplate::onStepIn(), 0 passed in /Users/rabol/code/web/sign/vendor/vildanbina/livewire-wizard/src/Concerns/HasHooks.php on line 13 and exactly 2 expected

**Comment by vildanbina** [comment]
@rabol the issue has already been fixed in version 2.1. Please revisit the README.md to get the latest updates
