### ISSUE TITLE
Cannot get value of fields in previous steps in the next step.

### ISSUE THREAD

**Issue by zeevx** [vildanbina/livewire-wizard#2]
Hi, please...how can I get the value of fields in previous steps in the next step? 
Example:
Step 1: input: name
Step 2: input: email => (I want to display the name from step one on the page of step 2)

**Comment by vildanbina** [comment]
All data will be store in `$state` variable to livewire component. 
From step class you can access $state variable in this way: `$this->getLivewire()->getState()`
