### ISSUE TITLE
Add support for livewire 3.0

### ISSUE THREAD

**Issue by qwasyx0** [vildanbina/livewire-wizard#20]
Package cannot be upgraded with livewire 3.0:

 vildanbina/livewire-wizard[v1.2, ..., v1.2.3] require livewire/livewire ^2.0 -> found livewire/livewire[v2.0.0, ..., 2.x-dev] but it conflicts with your root composer.json require (^3.0).
    - Root composer.json requires vildanbina/livewire-wizard ^1.2 -> satisfiable by vildanbina/livewire-wizard[v1.2, v1.2.1, v1.2.2, v1.2.3].

**Comment by nextun** [comment]
Any update on this ticket ?

**Comment by vildanbina** [comment]
thank you for bringing this to our attention.

I've released a new version to ensure compatibility with Livewire 3.

You can check it out here: [Livewire Wizard Release v2.0](https://github.com/vildanbina/livewire-wizard/releases/tag/v2.0).
