### ISSUE TITLE
 Is it possible to manage the change of state of each element of the form?

### ISSUE THREAD

**Issue by Fabio-Paccosi** [vildanbina/livewire-wizard#23]
Hi,

I would need to save the state for each element of the wizard form at each modification.

I tried using wire:change but it doesn't work as it doesn't find the method in the step controller.

Do you have any idea?

A thousand thanks

**Comment by vildanbina** [comment]
HI @Fabio-Paccosi,

To save the state of each element in the wizard form whenever it is modified, you should use `wire:model="state.{FIELD}"`, where `{FIELD}` is the key of your state inside Wizard Component. This will automatically bind the input field to the component's state.
