### ISSUE TITLE
Call to undefined function Vildanbina\LivewireWizard\str()

### ISSUE THREAD

**Issue by CorySheppard** [vildanbina/livewire-wizard#5]
Hey, 

Currently getting an error whenever I attempt to input something into an input field with a `wire:model="state.example"`. I get this error: `Call to undefined function Vildanbina\LivewireWizard\str()` and it points me to the `vendor/vildanbina/livewire-wizard/src/WizardComponent.php` page on line 129 where it has `$name = str($name);`. All I'm doing is using the wire model like I've shown above, and on my save function I have

```
$model = $this-model;

$model->example = $state['example'];

$model->save();
```

and on my validation I'm doing this

```
return [
    [
        'state.example' => ['required']
    ],
    [
        'state.example' => __('Example')
    ]
]
```

This is creating a new model/entry so when using the wizard I've left it blank, e.g. `<livewire:verify-wizard />`.

**Comment by vildanbina** [comment]
Because in your app doesn't exists `str` function. In new release of package i fixed this issue by replacing `str` function with `Str::of($str)`. https://github.com/vildanbina/livewire-wizard/releases/tag/v1.2.1
