### ISSUE TITLE
Have problem emitting from Javascript inside a step back to the component

### ISSUE THREAD

**Issue by andreaskviby** [vildanbina/livewire-wizard#8]
I am working on a step where the user will be able to take a photo by using the camera. That is already working and the camera shows up and everything. BUT... 

window.livewire.emit('storePhoto', canvas.toDataURL());

That line is doing nothing and it doesn't matter if I test 

this.Livewire.emit('storePhoto', canvas.toDataURL());

or...

Livewire.emit('storePhoto', canvas.toDataURL());

Nothing happens and yes I have the protected $listeners setup and everything. Do you have any idea why I can't emit data to a function inside a step using the wizard?

**Comment by vildanbina** [comment]
First, that issue doesn't come from our package so I think you're doing any basic mistake. Please check in detail how listeners works in livewire documentation. 
When I don't have full code, I cannot tell something.
