### ISSUE TITLE
Adding custom function to the Step to manipulate the state

### ISSUE THREAD

**Issue by gozbert** [vildanbina/livewire-wizard#9]
Can you assit i need a way to call the addToCollection function from the step view but it's complain that method not found since i need to maintain all the action that are happening with the step being done in the given Step

```
public function mount()
    {
        $this->mergeState([
            'locations' => collect([
                [
                    'name' => '',
                ]
            ])
        ]);
    }

```

// 
```

 public function addToCollection()
    {
        $this->state['locations']->push(['name' => '']);
    }

```
```
    public function removeFromCollection($key)
    {
        $this->state['locations']->pull($key);
    }
```

**Comment by affektde** [comment]
This would be interesting for dynamic input fields.

I try to loop over a collection of dynamic fields and have trouble with all the array keys.

I have something like this, to add fields dynamically.

```php
/* addArtist($id, $participationId) */
$artists = $this->getState()['artists'];
$artists[] = [
    'id' => $id,
    'pivot' => [
        'participation_id' => $participationId,
    ]
];
$this->state['artists'] = $artists;
```

```blade
@foreach($this->state['artists'] as $artist)
    <li wire:key="artist{{ $artist['id'] }}">
        <input wire:model="state.artists.{{ $loop->index }}.id" />
    </li>
@endforeach
```

Like issue title says: "Adding custom function to the Step to manipulate the state"

How to manipulate the state within a public method in our WizardComponent.

Like @gozbert 's method `removeFromCollection` `$this->state['locations']` will not reflect state on the frontend.

**Comment by affektde** [comment]
Ok I've got it working with:

```php
    public function deleteArtist($index)
    {
        $artists = $this->getState()['artists'];
        unset($artists[$index]);
        $this->state['artists'] = array_values($artists);
        $this->putState(
            'artists',
            array_values($artists)
        );
    }
```
`putState()` needs to be called additionally. To be in sync with Livewire I think.

So @gozbert maybe this is working for you? Not tested, just my idea.

```php
    public function removeFromCollection($key)
    {
        $this->state['locations']->pull($key);
        $this->putState(
            'locations',
            $this->state['locations']
        );
    }
```

**Comment by gozbert** [comment]
@affektde  if you add the function in the class which extends WizardComponent that function will be available on the view
Example 
`
class Apply extends WizardComponent{

    public function removeFromCollection($key)
    {
        $this->state['locations']->pull($key);
        $this->putState(
            'locations',
            $this->state['locations']
        );
    }
}
`
removeFromCollection() function will be available in every Steps view that  you have so this will work if all of your function will be defined in the parent class of the Steps

What i need is the way that I can group the logic of the Step within the Step class without adding it to the parent that will help in grouping the logic.

**Comment by affektde** [comment]
Ok now I understand @gozbert.

`Step` is not a Livewire component. It extends `ViewComponent`.

So we need somehow to hook into parent's `WizardComponent` Livewire.

I think this is a feature and we could develop a PR. Investigating the code design with those `Step`- classes and `ViewComponent`.

**Comment by gozbert** [comment]
@affektde Yes, you are right
